spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true

# Affiche les requêtes SQL exécutées par Hibernate
spring.jpa.show-sql=true

# Formatte les requêtes SQL pour une meilleure lisibilité
spring.jpa.properties.hibernate.format_sql=true

# Active les logs pour les requêtes SQL générées par Hibernate
logging.level.org.hibernate.SQL=DEBUG

# Affiche les paramètres des requêtes SQL
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
